name = "NumLinAlg"
uuid = "3f17a822-8c89-415e-927c-c51e25630e14"
repo = "git@github.com:numlinalg/NumLingAlg.git"
description = "Local registry for numlinalg organization packages."

[packages]
da1d211a-c3bc-43b2-b5d0-ce83f16a0f3a = { name = "RLinearAlgebra", path = "R/RLinearAlgebra" }
